version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres-dev:
    image: postgres:15-alpine
    container_name: urutibiz-postgres-dev
    environment:
      POSTGRES_DB: urutibiz_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - urutibiz-dev-network

  # Redis Cache for Development
  redis-dev:
    image: redis:7-alpine
    container_name: urutibiz-redis-dev
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - urutibiz-dev-network

  # pgAdmin for Database Management
  pgadmin:
    image: dpage/pgadmin4
    container_name: urutibiz-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@urutibiz.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres-dev
    restart: unless-stopped
    networks:
      - urutibiz-dev-network

  # Redis Commander for Redis Management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: urutibiz-redis-commander
    environment:
      REDIS_HOSTS: local:redis-dev:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis-dev
    restart: unless-stopped
    networks:
      - urutibiz-dev-network

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  urutibiz-dev-network:
    driver: bridge
